export const InstrumentList = [
    'vocals',
    'lead vocals',
    'background vocals',
    'backing vocals',
    'singing',
    'choir',
    'spoken word',
    'screams',
    'growls',
    'chants',
    'shouts',
    'yells',
    'all vocals',
    'guitar',
    'acoustic guitar',
    'electric guitar',
    '12 string guitar',
    '12 string acoustic guitar',
    '12 string electric guitar',
    'ukulele',
    'mandolin',
    'banjo',
    'fiddle',
    'sitar',
    'acoustic sitar',
    'electric sitar',
    'baritone guitar',
    'lap steel guitar',
    'pedal steel guitar',
    'slide guitar',
    'bottle neck guitar',
    'all guitars',
    'all electric guitars',
    'all acoustic guitars',
    'all electric and acoustic guitars',
    'all acoustic and electric guitars',
    'bass',
    'bass guitar',
    'electric bass',
    'electric bass guitar',
    'acoustic bass',
    'acoustic bass guitar',
    'double bass',
    'upright bass',
    'fretless bass',
    'all basses',
    'all electric basses',
    'all acoustic basses',
    'all electric and acoustic basses',
    'all acoustic and electric basses',
    'keyboard',
    'keyboards',
    'piano',
    'electric piano',
    'yamaha piano',
    'yamaha electric piano',
    'synthesizer',
    'clavinet',
    'melotron',
    'keytar',
    'wurlitzer',
    'organ',
    'church organ',
    'pipe organ',
    'hammond organ',
    'hammond b3 organ',
    'all keyboards',
    'drums',
    'snare drum',
    'kick drum',
    'timpani',
    'tambourine',
    'congas',
    'bongos',
    'shaker',
    'cowbell',
    'handclaps',
    'thumb clicks',
    'snaps',
    'thumb snaps',
    'finger clicks',
    'finger snaps',
    'glockenspiel',
    'xylophone',
    'tubular bells',
    'vibraphone',
    'marimba',
    'brass',
    'brass section',
    'trumpet',
    'trombone',
    'tuba',
    'flugelhorn',
    'cornet',
    'violin',
    'viola',
    'cello',
    'harp',
    'string section',
    'saxophone',
    'clarinet',
    'flute',
    'bassoon',
    'oboe',
    'piccolo',
    'bagpipe',
    'theremin',
    'harmonica',
    'kazoo',
    'didgeridoo',
    'dulcimer',
    'zither',
    'accordion',
    'glass harmonica',
    'all instruments'
]